### ISSUE TITLE
Compatibility with Jupyter 4.0

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/Interact.jl#73]
I was unable to get `Interact` to work with Jupyter 4.0.

Since there are rather nice new features being introduced into the Jupyter notebook, 
it would be great to be able to use `Interact.jl` with it.

**Comment by dlfivefifty** [comment]
+1

**Comment by mmoh** [comment]
Same here

**Comment by stevengj** [comment]
Did you try the `Pkg.checkout` version?

**Comment by mmoh** [comment]
@stevengj  Yes.  What happens in my notebook is after trying to run a cell using @manipulate,  the notebook becomes stuck with ``` In[*] ``` for that cell.

**Comment by Ken-B** [comment]
+1

**Comment by dlfivefifty** [comment]
It seems that lift still works.

**Comment by z-m-k** [comment]
@mmoh @stevengj Actually, although the notebook shows that it is busy with `In[*]` the kernel remains idle. After a refresh you can continue running code, just not `@manipulate`.

**Comment by shashi** [comment]
there have been some breaking changes in Jupyter's JavaScript and widget messaging.

@dlfivefifty that's good to know. actually that's the hacky part.

**Comment by shashi** [comment]
Done

**Comment by Ken-B** [comment]
This still doesn't work for me, it still shows busy with `In[*]`. I'm on jupyter 4.0.4, windows, latest v0.4-rc binary.

Should I reinstall something?

Thanks for working on this!

**Comment by shashi** [comment]
Did you try it in a fresh notebook?

**Comment by dlfivefifty** [comment]
It works for me after

	Pkg.checkout(“Interact”)

but now the sliders are horizontally aligned instead of vertically!

**Comment by shashi** [comment]
" now the sliders are horizontally aligned instead of vertically!" ???
It was always horizontal?

**Comment by Ken-B** [comment]
I found my issue, I just noticedipywidgets was not installed (it actually said so during jupyter startup):
```
[W 17:46:48.944 NotebookApp] ipywidgets package not installed.  Widgets are unavailable.
```
 After running `conda install jupyter` it works! I think previously I just installed `conda install ipython-notebook`. Also, for me the slider align just fine :)

Thanks again, Shashi!

**Comment by dlfivefifty** [comment]
I mean when you have multiple sliders

**Comment by garrison** [comment]
I just ran into this issue, even with the latest versions of each package.  @Ken-B's solution worked; apparently I did not have `jupyter` or `ipywidgets` installed.  It would be wonderful if this were recognized in the notebook and a warning were displayed instead of silent failure.

**Comment by dpsanders** [comment]
With `jupyter` and `ipywidgets`, (and some deprecation fixes I just sent) it's working perfectly in Jupyter 4. Many thanks! :cake:

**Comment by MikaelSlevinsky** [comment]
I just tried using this again, but code in my manipulate macros only gets updated when I depress the slider (which isn't very interactive). It used to evaluate continuously if I dragged the slider. Is this how it's currently working? or do I have a bug?

**Comment by dlfivefifty** [comment]
I have the same problem.
